// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.federal_c1.federal_client1.grpc;

public final class FederalProto {
  private FederalProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_Response_Arr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_example_Response_Arr_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rfederal.proto\022\007example\"E\n\007Request\022\n\n\002i" +
      "p\030\001 \001(\t\022\013\n\003url\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\023\n\013da" +
      "tainfoReq\030\004 \001(\t\"\226\002\n\010Response\022\n\n\002ip\030\001 \001(\t" +
      "\022\023\n\013datainfoRet\030\002 \001(\t\022\014\n\004time\030\003 \001(\t\022\t\n\001n" +
      "\030\004 \001(\005\022\n\n\002n2\030\005 \001(\005\022\n\n\002n3\030\006 \001(\005\022\n\n\002x1\030\007 \003" +
      "(\t\022\n\n\002y1\030\010 \003(\005\022\n\n\002r1\030\t \001(\005\022\n\n\002r2\030\n \001(\005\022\n" +
      "\n\002r3\030\013 \001(\005\022\013\n\003r21\030\014 \001(\005\022\013\n\003r22\030\r \001(\005\022\n\n\002" +
      "c1\030\016 \001(\005\022\n\n\002c2\030\017 \001(\005\022\017\n\007columns\030\020 \003(\t\022\"\n" +
      "\003arr\030\022 \003(\0132\025.example.Response.Arr\032\025\n\003Arr" +
      "\022\016\n\006values\030\021 \003(\0012v\n\020ArithmeticServer\022/\n\010" +
      "dataInfo\022\020.example.Request\032\021.example.Res" +
      "ponse\0221\n\nlocalTrain\022\020.example.Request\032\021." +
      "example.ResponseB\"\n\020com.example.grpcB\014Fe" +
      "deralProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_example_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_example_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Request_descriptor,
        new java.lang.String[] { "Ip", "Url", "Type", "DatainfoReq", });
    internal_static_example_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_example_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Response_descriptor,
        new java.lang.String[] { "Ip", "DatainfoRet", "Time", "N", "N2", "N3", "X1", "Y1", "R1", "R2", "R3", "R21", "R22", "C1", "C2", "Columns", "Arr", });
    internal_static_example_Response_Arr_descriptor =
      internal_static_example_Response_descriptor.getNestedTypes().get(0);
    internal_static_example_Response_Arr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_example_Response_Arr_descriptor,
        new java.lang.String[] { "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
