// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.federal_c1.federal_client1.grpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * 数据传输的变量
   * </pre>
   *
   * <code>string datainfoRet = 2;</code>
   */
  java.lang.String getDatainfoRet();
  /**
   * <pre>
   * 数据传输的变量
   * </pre>
   *
   * <code>string datainfoRet = 2;</code>
   */
  com.google.protobuf.ByteString
      getDatainfoRetBytes();

  /**
   * <pre>
   * 模型运行的时间
   * </pre>
   *
   * <code>string time = 3;</code>
   */
  java.lang.String getTime();
  /**
   * <pre>
   * 模型运行的时间
   * </pre>
   *
   * <code>string time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <pre>
   * n 总样本数量
   * </pre>
   *
   * <code>int32 n = 4;</code>
   */
  int getN();

  /**
   * <pre>
   * n2 样本类别种类
   * </pre>
   *
   * <code>int32 n2 = 5;</code>
   */
  int getN2();

  /**
   * <pre>
   * n3 特征数量
   * </pre>
   *
   * <code>int32 n3 = 6;</code>
   */
  int getN3();

  /**
   * <pre>
   * x1 样本类别种类
   * </pre>
   *
   * <code>repeated string x1 = 7;</code>
   */
  java.util.List<java.lang.String>
      getX1List();
  /**
   * <pre>
   * x1 样本类别种类
   * </pre>
   *
   * <code>repeated string x1 = 7;</code>
   */
  int getX1Count();
  /**
   * <pre>
   * x1 样本类别种类
   * </pre>
   *
   * <code>repeated string x1 = 7;</code>
   */
  java.lang.String getX1(int index);
  /**
   * <pre>
   * x1 样本类别种类
   * </pre>
   *
   * <code>repeated string x1 = 7;</code>
   */
  com.google.protobuf.ByteString
      getX1Bytes(int index);

  /**
   * <pre>
   * y1 每类样本数量
   * </pre>
   *
   * <code>repeated int32 y1 = 8;</code>
   */
  java.util.List<java.lang.Integer> getY1List();
  /**
   * <pre>
   * y1 每类样本数量
   * </pre>
   *
   * <code>repeated int32 y1 = 8;</code>
   */
  int getY1Count();
  /**
   * <pre>
   * y1 每类样本数量
   * </pre>
   *
   * <code>repeated int32 y1 = 8;</code>
   */
  int getY1(int index);

  /**
   * <pre>
   * r1 缺失值数量
   * </pre>
   *
   * <code>int32 r1 = 9;</code>
   */
  int getR1();

  /**
   * <pre>
   * r2 异常值数量
   * </pre>
   *
   * <code>int32 r2 = 10;</code>
   */
  int getR2();

  /**
   * <pre>
   * r3 既不是缺失值也不是异常值占比（不可能同为缺失值和异常值)
   * </pre>
   *
   * <code>int32 r3 = 11;</code>
   */
  int getR3();

  /**
   * <pre>
   * r21 特征值中的字符数量
   * </pre>
   *
   * <code>int32 r21 = 12;</code>
   */
  int getR21();

  /**
   * <pre>
   * r22 特征值中非字符数据数量
   * </pre>
   *
   * <code>int32 r22 = 13;</code>
   */
  int getR22();

  /**
   * <pre>
   * c1 连续
   * </pre>
   *
   * <code>int32 c1 = 14;</code>
   */
  int getC1();

  /**
   * <pre>
   * c2 离散
   * </pre>
   *
   * <code>int32 c2 = 15;</code>
   */
  int getC2();

  /**
   * <code>repeated string columns = 16;</code>
   */
  java.util.List<java.lang.String>
      getColumnsList();
  /**
   * <code>repeated string columns = 16;</code>
   */
  int getColumnsCount();
  /**
   * <code>repeated string columns = 16;</code>
   */
  java.lang.String getColumns(int index);
  /**
   * <code>repeated string columns = 16;</code>
   */
  com.google.protobuf.ByteString
      getColumnsBytes(int index);

  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  java.util.List<Response.Arr>
      getArrList();
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  Response.Arr getArr(int index);
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  int getArrCount();
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  java.util.List<? extends Response.ArrOrBuilder>
      getArrOrBuilderList();
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  Response.ArrOrBuilder getArrOrBuilder(
      int index);
}
