// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.federal_c1.federal_client1.grpc;

/**
 * Protobuf type {@code example.Response}
 */
public  final class Response extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:example.Response)
    ResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Response.newBuilder() to construct.
  private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Response() {
    ip_ = "";
    datainfoRet_ = "";
    time_ = "";
    n_ = 0;
    n2_ = 0;
    n3_ = 0;
    x1_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    y1_ = java.util.Collections.emptyList();
    r1_ = 0;
    r2_ = 0;
    r3_ = 0;
    r21_ = 0;
    r22_ = 0;
    c1_ = 0;
    c2_ = 0;
    columns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    arr_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Response(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ip_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            datainfoRet_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            time_ = s;
            break;
          }
          case 32: {

            n_ = input.readInt32();
            break;
          }
          case 40: {

            n2_ = input.readInt32();
            break;
          }
          case 48: {

            n3_ = input.readInt32();
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              x1_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000040;
            }
            x1_.add(s);
            break;
          }
          case 64: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              y1_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000080;
            }
            y1_.add(input.readInt32());
            break;
          }
          case 66: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080) && input.getBytesUntilLimit() > 0) {
              y1_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000080;
            }
            while (input.getBytesUntilLimit() > 0) {
              y1_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          case 72: {

            r1_ = input.readInt32();
            break;
          }
          case 80: {

            r2_ = input.readInt32();
            break;
          }
          case 88: {

            r3_ = input.readInt32();
            break;
          }
          case 96: {

            r21_ = input.readInt32();
            break;
          }
          case 104: {

            r22_ = input.readInt32();
            break;
          }
          case 112: {

            c1_ = input.readInt32();
            break;
          }
          case 120: {

            c2_ = input.readInt32();
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00008000) == 0x00008000)) {
              columns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00008000;
            }
            columns_.add(s);
            break;
          }
          case 146: {
            if (!((mutable_bitField0_ & 0x00010000) == 0x00010000)) {
              arr_ = new java.util.ArrayList<Response.Arr>();
              mutable_bitField0_ |= 0x00010000;
            }
            arr_.add(
                input.readMessage(Response.Arr.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        x1_ = x1_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        y1_ = java.util.Collections.unmodifiableList(y1_);
      }
      if (((mutable_bitField0_ & 0x00008000) == 0x00008000)) {
        columns_ = columns_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00010000) == 0x00010000)) {
        arr_ = java.util.Collections.unmodifiableList(arr_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return FederalProto.internal_static_example_Response_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return FederalProto.internal_static_example_Response_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Response.class, Response.Builder.class);
  }

  public interface ArrOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.Response.Arr)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated double values = 17;</code>
     */
    java.util.List<java.lang.Double> getValuesList();
    /**
     * <code>repeated double values = 17;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated double values = 17;</code>
     */
    double getValues(int index);
  }
  /**
   * Protobuf type {@code example.Response.Arr}
   */
  public  static final class Arr extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:example.Response.Arr)
      ArrOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Arr.newBuilder() to construct.
    private Arr(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Arr() {
      values_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Arr(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 137: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                values_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              values_.add(input.readDouble());
              break;
            }
            case 138: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                values_ = new java.util.ArrayList<java.lang.Double>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                values_.add(input.readDouble());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = java.util.Collections.unmodifiableList(values_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FederalProto.internal_static_example_Response_Arr_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FederalProto.internal_static_example_Response_Arr_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.Arr.class, Response.Arr.Builder.class);
    }

    public static final int VALUES_FIELD_NUMBER = 17;
    private java.util.List<java.lang.Double> values_;
    /**
     * <code>repeated double values = 17;</code>
     */
    public java.util.List<java.lang.Double>
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated double values = 17;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated double values = 17;</code>
     */
    public double getValues(int index) {
      return values_.get(index);
    }
    private int valuesMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getValuesList().size() > 0) {
        output.writeUInt32NoTag(138);
        output.writeUInt32NoTag(valuesMemoizedSerializedSize);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeDoubleNoTag(values_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        dataSize = 8 * getValuesList().size();
        size += dataSize;
        if (!getValuesList().isEmpty()) {
          size += 2;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        valuesMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Response.Arr)) {
        return super.equals(obj);
      }
      Response.Arr other = (Response.Arr) obj;

      boolean result = true;
      result = result && getValuesList()
          .equals(other.getValuesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getValuesCount() > 0) {
        hash = (37 * hash) + VALUES_FIELD_NUMBER;
        hash = (53 * hash) + getValuesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Response.Arr parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response.Arr parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response.Arr parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response.Arr parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response.Arr parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Response.Arr parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Response.Arr parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response.Arr parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response.Arr parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Response.Arr parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Response.Arr parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Response.Arr parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Response.Arr prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.Response.Arr}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.Response.Arr)
        Response.ArrOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return FederalProto.internal_static_example_Response_Arr_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return FederalProto.internal_static_example_Response_Arr_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Response.Arr.class, Response.Arr.Builder.class);
      }

      // Construct using com.federal_c1.federal_client1.grpc.Response.Arr.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return FederalProto.internal_static_example_Response_Arr_descriptor;
      }

      public Response.Arr getDefaultInstanceForType() {
        return Response.Arr.getDefaultInstance();
      }

      public Response.Arr build() {
        Response.Arr result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Response.Arr buildPartial() {
        Response.Arr result = new Response.Arr(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = java.util.Collections.unmodifiableList(values_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.values_ = values_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Response.Arr) {
          return mergeFrom((Response.Arr)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Response.Arr other) {
        if (other == Response.Arr.getDefaultInstance()) return this;
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Response.Arr parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Response.Arr) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Double> values_ = java.util.Collections.emptyList();
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          values_ = new java.util.ArrayList<java.lang.Double>(values_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated double values = 17;</code>
       */
      public java.util.List<java.lang.Double>
          getValuesList() {
        return java.util.Collections.unmodifiableList(values_);
      }
      /**
       * <code>repeated double values = 17;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated double values = 17;</code>
       */
      public double getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated double values = 17;</code>
       */
      public Builder setValues(
          int index, double value) {
        ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double values = 17;</code>
       */
      public Builder addValues(double value) {
        ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double values = 17;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<? extends java.lang.Double> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated double values = 17;</code>
       */
      public Builder clearValues() {
        values_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:example.Response.Arr)
    }

    // @@protoc_insertion_point(class_scope:example.Response.Arr)
    private static final Response.Arr DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Response.Arr();
    }

    public static Response.Arr getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Arr>
        PARSER = new com.google.protobuf.AbstractParser<Arr>() {
      public Arr parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Arr(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Arr> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Arr> getParserForType() {
      return PARSER;
    }

    public Response.Arr getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int IP_FIELD_NUMBER = 1;
  private volatile java.lang.Object ip_;
  /**
   * <code>string ip = 1;</code>
   */
  public java.lang.String getIp() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ip_ = s;
      return s;
    }
  }
  /**
   * <code>string ip = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIpBytes() {
    java.lang.Object ref = ip_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ip_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATAINFORET_FIELD_NUMBER = 2;
  private volatile java.lang.Object datainfoRet_;
  /**
   * <pre>
   * 数据传输的变量
   * </pre>
   *
   * <code>string datainfoRet = 2;</code>
   */
  public java.lang.String getDatainfoRet() {
    java.lang.Object ref = datainfoRet_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      datainfoRet_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 数据传输的变量
   * </pre>
   *
   * <code>string datainfoRet = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDatainfoRetBytes() {
    java.lang.Object ref = datainfoRet_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datainfoRet_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_FIELD_NUMBER = 3;
  private volatile java.lang.Object time_;
  /**
   * <pre>
   * 模型运行的时间
   * </pre>
   *
   * <code>string time = 3;</code>
   */
  public java.lang.String getTime() {
    java.lang.Object ref = time_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      time_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 模型运行的时间
   * </pre>
   *
   * <code>string time = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTimeBytes() {
    java.lang.Object ref = time_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      time_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int N_FIELD_NUMBER = 4;
  private int n_;
  /**
   * <pre>
   * n 总样本数量
   * </pre>
   *
   * <code>int32 n = 4;</code>
   */
  public int getN() {
    return n_;
  }

  public static final int N2_FIELD_NUMBER = 5;
  private int n2_;
  /**
   * <pre>
   * n2 样本类别种类
   * </pre>
   *
   * <code>int32 n2 = 5;</code>
   */
  public int getN2() {
    return n2_;
  }

  public static final int N3_FIELD_NUMBER = 6;
  private int n3_;
  /**
   * <pre>
   * n3 特征数量
   * </pre>
   *
   * <code>int32 n3 = 6;</code>
   */
  public int getN3() {
    return n3_;
  }

  public static final int X1_FIELD_NUMBER = 7;
  private com.google.protobuf.LazyStringList x1_;
  /**
   * <pre>
   * x1 样本类别种类
   * </pre>
   *
   * <code>repeated string x1 = 7;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getX1List() {
    return x1_;
  }
  /**
   * <pre>
   * x1 样本类别种类
   * </pre>
   *
   * <code>repeated string x1 = 7;</code>
   */
  public int getX1Count() {
    return x1_.size();
  }
  /**
   * <pre>
   * x1 样本类别种类
   * </pre>
   *
   * <code>repeated string x1 = 7;</code>
   */
  public java.lang.String getX1(int index) {
    return x1_.get(index);
  }
  /**
   * <pre>
   * x1 样本类别种类
   * </pre>
   *
   * <code>repeated string x1 = 7;</code>
   */
  public com.google.protobuf.ByteString
      getX1Bytes(int index) {
    return x1_.getByteString(index);
  }

  public static final int Y1_FIELD_NUMBER = 8;
  private java.util.List<java.lang.Integer> y1_;
  /**
   * <pre>
   * y1 每类样本数量
   * </pre>
   *
   * <code>repeated int32 y1 = 8;</code>
   */
  public java.util.List<java.lang.Integer>
      getY1List() {
    return y1_;
  }
  /**
   * <pre>
   * y1 每类样本数量
   * </pre>
   *
   * <code>repeated int32 y1 = 8;</code>
   */
  public int getY1Count() {
    return y1_.size();
  }
  /**
   * <pre>
   * y1 每类样本数量
   * </pre>
   *
   * <code>repeated int32 y1 = 8;</code>
   */
  public int getY1(int index) {
    return y1_.get(index);
  }
  private int y1MemoizedSerializedSize = -1;

  public static final int R1_FIELD_NUMBER = 9;
  private int r1_;
  /**
   * <pre>
   * r1 缺失值数量
   * </pre>
   *
   * <code>int32 r1 = 9;</code>
   */
  public int getR1() {
    return r1_;
  }

  public static final int R2_FIELD_NUMBER = 10;
  private int r2_;
  /**
   * <pre>
   * r2 异常值数量
   * </pre>
   *
   * <code>int32 r2 = 10;</code>
   */
  public int getR2() {
    return r2_;
  }

  public static final int R3_FIELD_NUMBER = 11;
  private int r3_;
  /**
   * <pre>
   * r3 既不是缺失值也不是异常值占比（不可能同为缺失值和异常值)
   * </pre>
   *
   * <code>int32 r3 = 11;</code>
   */
  public int getR3() {
    return r3_;
  }

  public static final int R21_FIELD_NUMBER = 12;
  private int r21_;
  /**
   * <pre>
   * r21 特征值中的字符数量
   * </pre>
   *
   * <code>int32 r21 = 12;</code>
   */
  public int getR21() {
    return r21_;
  }

  public static final int R22_FIELD_NUMBER = 13;
  private int r22_;
  /**
   * <pre>
   * r22 特征值中非字符数据数量
   * </pre>
   *
   * <code>int32 r22 = 13;</code>
   */
  public int getR22() {
    return r22_;
  }

  public static final int C1_FIELD_NUMBER = 14;
  private int c1_;
  /**
   * <pre>
   * c1 连续
   * </pre>
   *
   * <code>int32 c1 = 14;</code>
   */
  public int getC1() {
    return c1_;
  }

  public static final int C2_FIELD_NUMBER = 15;
  private int c2_;
  /**
   * <pre>
   * c2 离散
   * </pre>
   *
   * <code>int32 c2 = 15;</code>
   */
  public int getC2() {
    return c2_;
  }

  public static final int COLUMNS_FIELD_NUMBER = 16;
  private com.google.protobuf.LazyStringList columns_;
  /**
   * <code>repeated string columns = 16;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getColumnsList() {
    return columns_;
  }
  /**
   * <code>repeated string columns = 16;</code>
   */
  public int getColumnsCount() {
    return columns_.size();
  }
  /**
   * <code>repeated string columns = 16;</code>
   */
  public java.lang.String getColumns(int index) {
    return columns_.get(index);
  }
  /**
   * <code>repeated string columns = 16;</code>
   */
  public com.google.protobuf.ByteString
      getColumnsBytes(int index) {
    return columns_.getByteString(index);
  }

  public static final int ARR_FIELD_NUMBER = 18;
  private java.util.List<Response.Arr> arr_;
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  public java.util.List<Response.Arr> getArrList() {
    return arr_;
  }
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  public java.util.List<? extends Response.ArrOrBuilder>
      getArrOrBuilderList() {
    return arr_;
  }
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  public int getArrCount() {
    return arr_.size();
  }
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  public Response.Arr getArr(int index) {
    return arr_.get(index);
  }
  /**
   * <code>repeated .example.Response.Arr arr = 18;</code>
   */
  public Response.ArrOrBuilder getArrOrBuilder(
      int index) {
    return arr_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
    }
    if (!getDatainfoRetBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, datainfoRet_);
    }
    if (!getTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, time_);
    }
    if (n_ != 0) {
      output.writeInt32(4, n_);
    }
    if (n2_ != 0) {
      output.writeInt32(5, n2_);
    }
    if (n3_ != 0) {
      output.writeInt32(6, n3_);
    }
    for (int i = 0; i < x1_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, x1_.getRaw(i));
    }
    if (getY1List().size() > 0) {
      output.writeUInt32NoTag(66);
      output.writeUInt32NoTag(y1MemoizedSerializedSize);
    }
    for (int i = 0; i < y1_.size(); i++) {
      output.writeInt32NoTag(y1_.get(i));
    }
    if (r1_ != 0) {
      output.writeInt32(9, r1_);
    }
    if (r2_ != 0) {
      output.writeInt32(10, r2_);
    }
    if (r3_ != 0) {
      output.writeInt32(11, r3_);
    }
    if (r21_ != 0) {
      output.writeInt32(12, r21_);
    }
    if (r22_ != 0) {
      output.writeInt32(13, r22_);
    }
    if (c1_ != 0) {
      output.writeInt32(14, c1_);
    }
    if (c2_ != 0) {
      output.writeInt32(15, c2_);
    }
    for (int i = 0; i < columns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, columns_.getRaw(i));
    }
    for (int i = 0; i < arr_.size(); i++) {
      output.writeMessage(18, arr_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
    }
    if (!getDatainfoRetBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, datainfoRet_);
    }
    if (!getTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, time_);
    }
    if (n_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, n_);
    }
    if (n2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, n2_);
    }
    if (n3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, n3_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < x1_.size(); i++) {
        dataSize += computeStringSizeNoTag(x1_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getX1List().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < y1_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(y1_.get(i));
      }
      size += dataSize;
      if (!getY1List().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      y1MemoizedSerializedSize = dataSize;
    }
    if (r1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, r1_);
    }
    if (r2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, r2_);
    }
    if (r3_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, r3_);
    }
    if (r21_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, r21_);
    }
    if (r22_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, r22_);
    }
    if (c1_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, c1_);
    }
    if (c2_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, c2_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < columns_.size(); i++) {
        dataSize += computeStringSizeNoTag(columns_.getRaw(i));
      }
      size += dataSize;
      size += 2 * getColumnsList().size();
    }
    for (int i = 0; i < arr_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(18, arr_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Response)) {
      return super.equals(obj);
    }
    Response other = (Response) obj;

    boolean result = true;
    result = result && getIp()
        .equals(other.getIp());
    result = result && getDatainfoRet()
        .equals(other.getDatainfoRet());
    result = result && getTime()
        .equals(other.getTime());
    result = result && (getN()
        == other.getN());
    result = result && (getN2()
        == other.getN2());
    result = result && (getN3()
        == other.getN3());
    result = result && getX1List()
        .equals(other.getX1List());
    result = result && getY1List()
        .equals(other.getY1List());
    result = result && (getR1()
        == other.getR1());
    result = result && (getR2()
        == other.getR2());
    result = result && (getR3()
        == other.getR3());
    result = result && (getR21()
        == other.getR21());
    result = result && (getR22()
        == other.getR22());
    result = result && (getC1()
        == other.getC1());
    result = result && (getC2()
        == other.getC2());
    result = result && getColumnsList()
        .equals(other.getColumnsList());
    result = result && getArrList()
        .equals(other.getArrList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IP_FIELD_NUMBER;
    hash = (53 * hash) + getIp().hashCode();
    hash = (37 * hash) + DATAINFORET_FIELD_NUMBER;
    hash = (53 * hash) + getDatainfoRet().hashCode();
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime().hashCode();
    hash = (37 * hash) + N_FIELD_NUMBER;
    hash = (53 * hash) + getN();
    hash = (37 * hash) + N2_FIELD_NUMBER;
    hash = (53 * hash) + getN2();
    hash = (37 * hash) + N3_FIELD_NUMBER;
    hash = (53 * hash) + getN3();
    if (getX1Count() > 0) {
      hash = (37 * hash) + X1_FIELD_NUMBER;
      hash = (53 * hash) + getX1List().hashCode();
    }
    if (getY1Count() > 0) {
      hash = (37 * hash) + Y1_FIELD_NUMBER;
      hash = (53 * hash) + getY1List().hashCode();
    }
    hash = (37 * hash) + R1_FIELD_NUMBER;
    hash = (53 * hash) + getR1();
    hash = (37 * hash) + R2_FIELD_NUMBER;
    hash = (53 * hash) + getR2();
    hash = (37 * hash) + R3_FIELD_NUMBER;
    hash = (53 * hash) + getR3();
    hash = (37 * hash) + R21_FIELD_NUMBER;
    hash = (53 * hash) + getR21();
    hash = (37 * hash) + R22_FIELD_NUMBER;
    hash = (53 * hash) + getR22();
    hash = (37 * hash) + C1_FIELD_NUMBER;
    hash = (53 * hash) + getC1();
    hash = (37 * hash) + C2_FIELD_NUMBER;
    hash = (53 * hash) + getC2();
    if (getColumnsCount() > 0) {
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumnsList().hashCode();
    }
    if (getArrCount() > 0) {
      hash = (37 * hash) + ARR_FIELD_NUMBER;
      hash = (53 * hash) + getArrList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Response parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Response parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Response parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Response parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Response parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Response parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Response parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Response parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Response prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code example.Response}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:example.Response)
          ResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return FederalProto.internal_static_example_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return FederalProto.internal_static_example_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Response.class, Response.Builder.class);
    }

    // Construct using com.federal_c1.federal_client1.grpc.Response.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getArrFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      ip_ = "";

      datainfoRet_ = "";

      time_ = "";

      n_ = 0;

      n2_ = 0;

      n3_ = 0;

      x1_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      y1_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);
      r1_ = 0;

      r2_ = 0;

      r3_ = 0;

      r21_ = 0;

      r22_ = 0;

      c1_ = 0;

      c2_ = 0;

      columns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00008000);
      if (arrBuilder_ == null) {
        arr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00010000);
      } else {
        arrBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return FederalProto.internal_static_example_Response_descriptor;
    }

    public Response getDefaultInstanceForType() {
      return Response.getDefaultInstance();
    }

    public Response build() {
      Response result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public Response buildPartial() {
      Response result = new Response(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.ip_ = ip_;
      result.datainfoRet_ = datainfoRet_;
      result.time_ = time_;
      result.n_ = n_;
      result.n2_ = n2_;
      result.n3_ = n3_;
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        x1_ = x1_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000040);
      }
      result.x1_ = x1_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        y1_ = java.util.Collections.unmodifiableList(y1_);
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.y1_ = y1_;
      result.r1_ = r1_;
      result.r2_ = r2_;
      result.r3_ = r3_;
      result.r21_ = r21_;
      result.r22_ = r22_;
      result.c1_ = c1_;
      result.c2_ = c2_;
      if (((bitField0_ & 0x00008000) == 0x00008000)) {
        columns_ = columns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00008000);
      }
      result.columns_ = columns_;
      if (arrBuilder_ == null) {
        if (((bitField0_ & 0x00010000) == 0x00010000)) {
          arr_ = java.util.Collections.unmodifiableList(arr_);
          bitField0_ = (bitField0_ & ~0x00010000);
        }
        result.arr_ = arr_;
      } else {
        result.arr_ = arrBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Response) {
        return mergeFrom((Response)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Response other) {
      if (other == Response.getDefaultInstance()) return this;
      if (!other.getIp().isEmpty()) {
        ip_ = other.ip_;
        onChanged();
      }
      if (!other.getDatainfoRet().isEmpty()) {
        datainfoRet_ = other.datainfoRet_;
        onChanged();
      }
      if (!other.getTime().isEmpty()) {
        time_ = other.time_;
        onChanged();
      }
      if (other.getN() != 0) {
        setN(other.getN());
      }
      if (other.getN2() != 0) {
        setN2(other.getN2());
      }
      if (other.getN3() != 0) {
        setN3(other.getN3());
      }
      if (!other.x1_.isEmpty()) {
        if (x1_.isEmpty()) {
          x1_ = other.x1_;
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          ensureX1IsMutable();
          x1_.addAll(other.x1_);
        }
        onChanged();
      }
      if (!other.y1_.isEmpty()) {
        if (y1_.isEmpty()) {
          y1_ = other.y1_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureY1IsMutable();
          y1_.addAll(other.y1_);
        }
        onChanged();
      }
      if (other.getR1() != 0) {
        setR1(other.getR1());
      }
      if (other.getR2() != 0) {
        setR2(other.getR2());
      }
      if (other.getR3() != 0) {
        setR3(other.getR3());
      }
      if (other.getR21() != 0) {
        setR21(other.getR21());
      }
      if (other.getR22() != 0) {
        setR22(other.getR22());
      }
      if (other.getC1() != 0) {
        setC1(other.getC1());
      }
      if (other.getC2() != 0) {
        setC2(other.getC2());
      }
      if (!other.columns_.isEmpty()) {
        if (columns_.isEmpty()) {
          columns_ = other.columns_;
          bitField0_ = (bitField0_ & ~0x00008000);
        } else {
          ensureColumnsIsMutable();
          columns_.addAll(other.columns_);
        }
        onChanged();
      }
      if (arrBuilder_ == null) {
        if (!other.arr_.isEmpty()) {
          if (arr_.isEmpty()) {
            arr_ = other.arr_;
            bitField0_ = (bitField0_ & ~0x00010000);
          } else {
            ensureArrIsMutable();
            arr_.addAll(other.arr_);
          }
          onChanged();
        }
      } else {
        if (!other.arr_.isEmpty()) {
          if (arrBuilder_.isEmpty()) {
            arrBuilder_.dispose();
            arrBuilder_ = null;
            arr_ = other.arr_;
            bitField0_ = (bitField0_ & ~0x00010000);
            arrBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArrFieldBuilder() : null;
          } else {
            arrBuilder_.addAllMessages(other.arr_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Response parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Response) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object ip_ = "";
    /**
     * <code>string ip = 1;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ip = 1;</code>
     */
    public Builder setIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 1;</code>
     */
    public Builder clearIp() {
      
      ip_ = getDefaultInstance().getIp();
      onChanged();
      return this;
    }
    /**
     * <code>string ip = 1;</code>
     */
    public Builder setIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object datainfoRet_ = "";
    /**
     * <pre>
     * 数据传输的变量
     * </pre>
     *
     * <code>string datainfoRet = 2;</code>
     */
    public java.lang.String getDatainfoRet() {
      java.lang.Object ref = datainfoRet_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        datainfoRet_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 数据传输的变量
     * </pre>
     *
     * <code>string datainfoRet = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDatainfoRetBytes() {
      java.lang.Object ref = datainfoRet_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datainfoRet_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 数据传输的变量
     * </pre>
     *
     * <code>string datainfoRet = 2;</code>
     */
    public Builder setDatainfoRet(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      datainfoRet_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据传输的变量
     * </pre>
     *
     * <code>string datainfoRet = 2;</code>
     */
    public Builder clearDatainfoRet() {
      
      datainfoRet_ = getDefaultInstance().getDatainfoRet();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 数据传输的变量
     * </pre>
     *
     * <code>string datainfoRet = 2;</code>
     */
    public Builder setDatainfoRetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      datainfoRet_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object time_ = "";
    /**
     * <pre>
     * 模型运行的时间
     * </pre>
     *
     * <code>string time = 3;</code>
     */
    public java.lang.String getTime() {
      java.lang.Object ref = time_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        time_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 模型运行的时间
     * </pre>
     *
     * <code>string time = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimeBytes() {
      java.lang.Object ref = time_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        time_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 模型运行的时间
     * </pre>
     *
     * <code>string time = 3;</code>
     */
    public Builder setTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模型运行的时间
     * </pre>
     *
     * <code>string time = 3;</code>
     */
    public Builder clearTime() {
      
      time_ = getDefaultInstance().getTime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 模型运行的时间
     * </pre>
     *
     * <code>string time = 3;</code>
     */
    public Builder setTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      time_ = value;
      onChanged();
      return this;
    }

    private int n_ ;
    /**
     * <pre>
     * n 总样本数量
     * </pre>
     *
     * <code>int32 n = 4;</code>
     */
    public int getN() {
      return n_;
    }
    /**
     * <pre>
     * n 总样本数量
     * </pre>
     *
     * <code>int32 n = 4;</code>
     */
    public Builder setN(int value) {
      
      n_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * n 总样本数量
     * </pre>
     *
     * <code>int32 n = 4;</code>
     */
    public Builder clearN() {
      
      n_ = 0;
      onChanged();
      return this;
    }

    private int n2_ ;
    /**
     * <pre>
     * n2 样本类别种类
     * </pre>
     *
     * <code>int32 n2 = 5;</code>
     */
    public int getN2() {
      return n2_;
    }
    /**
     * <pre>
     * n2 样本类别种类
     * </pre>
     *
     * <code>int32 n2 = 5;</code>
     */
    public Builder setN2(int value) {
      
      n2_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * n2 样本类别种类
     * </pre>
     *
     * <code>int32 n2 = 5;</code>
     */
    public Builder clearN2() {
      
      n2_ = 0;
      onChanged();
      return this;
    }

    private int n3_ ;
    /**
     * <pre>
     * n3 特征数量
     * </pre>
     *
     * <code>int32 n3 = 6;</code>
     */
    public int getN3() {
      return n3_;
    }
    /**
     * <pre>
     * n3 特征数量
     * </pre>
     *
     * <code>int32 n3 = 6;</code>
     */
    public Builder setN3(int value) {
      
      n3_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * n3 特征数量
     * </pre>
     *
     * <code>int32 n3 = 6;</code>
     */
    public Builder clearN3() {
      
      n3_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList x1_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureX1IsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        x1_ = new com.google.protobuf.LazyStringArrayList(x1_);
        bitField0_ |= 0x00000040;
       }
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getX1List() {
      return x1_.getUnmodifiableView();
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public int getX1Count() {
      return x1_.size();
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public java.lang.String getX1(int index) {
      return x1_.get(index);
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public com.google.protobuf.ByteString
        getX1Bytes(int index) {
      return x1_.getByteString(index);
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public Builder setX1(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureX1IsMutable();
      x1_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public Builder addX1(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureX1IsMutable();
      x1_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public Builder addAllX1(
        java.lang.Iterable<java.lang.String> values) {
      ensureX1IsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, x1_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public Builder clearX1() {
      x1_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * x1 样本类别种类
     * </pre>
     *
     * <code>repeated string x1 = 7;</code>
     */
    public Builder addX1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureX1IsMutable();
      x1_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> y1_ = java.util.Collections.emptyList();
    private void ensureY1IsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        y1_ = new java.util.ArrayList<java.lang.Integer>(y1_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <pre>
     * y1 每类样本数量
     * </pre>
     *
     * <code>repeated int32 y1 = 8;</code>
     */
    public java.util.List<java.lang.Integer>
        getY1List() {
      return java.util.Collections.unmodifiableList(y1_);
    }
    /**
     * <pre>
     * y1 每类样本数量
     * </pre>
     *
     * <code>repeated int32 y1 = 8;</code>
     */
    public int getY1Count() {
      return y1_.size();
    }
    /**
     * <pre>
     * y1 每类样本数量
     * </pre>
     *
     * <code>repeated int32 y1 = 8;</code>
     */
    public int getY1(int index) {
      return y1_.get(index);
    }
    /**
     * <pre>
     * y1 每类样本数量
     * </pre>
     *
     * <code>repeated int32 y1 = 8;</code>
     */
    public Builder setY1(
        int index, int value) {
      ensureY1IsMutable();
      y1_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * y1 每类样本数量
     * </pre>
     *
     * <code>repeated int32 y1 = 8;</code>
     */
    public Builder addY1(int value) {
      ensureY1IsMutable();
      y1_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * y1 每类样本数量
     * </pre>
     *
     * <code>repeated int32 y1 = 8;</code>
     */
    public Builder addAllY1(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureY1IsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, y1_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * y1 每类样本数量
     * </pre>
     *
     * <code>repeated int32 y1 = 8;</code>
     */
    public Builder clearY1() {
      y1_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }

    private int r1_ ;
    /**
     * <pre>
     * r1 缺失值数量
     * </pre>
     *
     * <code>int32 r1 = 9;</code>
     */
    public int getR1() {
      return r1_;
    }
    /**
     * <pre>
     * r1 缺失值数量
     * </pre>
     *
     * <code>int32 r1 = 9;</code>
     */
    public Builder setR1(int value) {
      
      r1_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * r1 缺失值数量
     * </pre>
     *
     * <code>int32 r1 = 9;</code>
     */
    public Builder clearR1() {
      
      r1_ = 0;
      onChanged();
      return this;
    }

    private int r2_ ;
    /**
     * <pre>
     * r2 异常值数量
     * </pre>
     *
     * <code>int32 r2 = 10;</code>
     */
    public int getR2() {
      return r2_;
    }
    /**
     * <pre>
     * r2 异常值数量
     * </pre>
     *
     * <code>int32 r2 = 10;</code>
     */
    public Builder setR2(int value) {
      
      r2_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * r2 异常值数量
     * </pre>
     *
     * <code>int32 r2 = 10;</code>
     */
    public Builder clearR2() {
      
      r2_ = 0;
      onChanged();
      return this;
    }

    private int r3_ ;
    /**
     * <pre>
     * r3 既不是缺失值也不是异常值占比（不可能同为缺失值和异常值)
     * </pre>
     *
     * <code>int32 r3 = 11;</code>
     */
    public int getR3() {
      return r3_;
    }
    /**
     * <pre>
     * r3 既不是缺失值也不是异常值占比（不可能同为缺失值和异常值)
     * </pre>
     *
     * <code>int32 r3 = 11;</code>
     */
    public Builder setR3(int value) {
      
      r3_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * r3 既不是缺失值也不是异常值占比（不可能同为缺失值和异常值)
     * </pre>
     *
     * <code>int32 r3 = 11;</code>
     */
    public Builder clearR3() {
      
      r3_ = 0;
      onChanged();
      return this;
    }

    private int r21_ ;
    /**
     * <pre>
     * r21 特征值中的字符数量
     * </pre>
     *
     * <code>int32 r21 = 12;</code>
     */
    public int getR21() {
      return r21_;
    }
    /**
     * <pre>
     * r21 特征值中的字符数量
     * </pre>
     *
     * <code>int32 r21 = 12;</code>
     */
    public Builder setR21(int value) {
      
      r21_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * r21 特征值中的字符数量
     * </pre>
     *
     * <code>int32 r21 = 12;</code>
     */
    public Builder clearR21() {
      
      r21_ = 0;
      onChanged();
      return this;
    }

    private int r22_ ;
    /**
     * <pre>
     * r22 特征值中非字符数据数量
     * </pre>
     *
     * <code>int32 r22 = 13;</code>
     */
    public int getR22() {
      return r22_;
    }
    /**
     * <pre>
     * r22 特征值中非字符数据数量
     * </pre>
     *
     * <code>int32 r22 = 13;</code>
     */
    public Builder setR22(int value) {
      
      r22_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * r22 特征值中非字符数据数量
     * </pre>
     *
     * <code>int32 r22 = 13;</code>
     */
    public Builder clearR22() {
      
      r22_ = 0;
      onChanged();
      return this;
    }

    private int c1_ ;
    /**
     * <pre>
     * c1 连续
     * </pre>
     *
     * <code>int32 c1 = 14;</code>
     */
    public int getC1() {
      return c1_;
    }
    /**
     * <pre>
     * c1 连续
     * </pre>
     *
     * <code>int32 c1 = 14;</code>
     */
    public Builder setC1(int value) {
      
      c1_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * c1 连续
     * </pre>
     *
     * <code>int32 c1 = 14;</code>
     */
    public Builder clearC1() {
      
      c1_ = 0;
      onChanged();
      return this;
    }

    private int c2_ ;
    /**
     * <pre>
     * c2 离散
     * </pre>
     *
     * <code>int32 c2 = 15;</code>
     */
    public int getC2() {
      return c2_;
    }
    /**
     * <pre>
     * c2 离散
     * </pre>
     *
     * <code>int32 c2 = 15;</code>
     */
    public Builder setC2(int value) {
      
      c2_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * c2 离散
     * </pre>
     *
     * <code>int32 c2 = 15;</code>
     */
    public Builder clearC2() {
      
      c2_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList columns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureColumnsIsMutable() {
      if (!((bitField0_ & 0x00008000) == 0x00008000)) {
        columns_ = new com.google.protobuf.LazyStringArrayList(columns_);
        bitField0_ |= 0x00008000;
       }
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getColumnsList() {
      return columns_.getUnmodifiableView();
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public int getColumnsCount() {
      return columns_.size();
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public java.lang.String getColumns(int index) {
      return columns_.get(index);
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public com.google.protobuf.ByteString
        getColumnsBytes(int index) {
      return columns_.getByteString(index);
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public Builder setColumns(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnsIsMutable();
      columns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public Builder addColumns(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColumnsIsMutable();
      columns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public Builder addAllColumns(
        java.lang.Iterable<java.lang.String> values) {
      ensureColumnsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, columns_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public Builder clearColumns() {
      columns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00008000);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string columns = 16;</code>
     */
    public Builder addColumnsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureColumnsIsMutable();
      columns_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<Response.Arr> arr_ =
      java.util.Collections.emptyList();
    private void ensureArrIsMutable() {
      if (!((bitField0_ & 0x00010000) == 0x00010000)) {
        arr_ = new java.util.ArrayList<Response.Arr>(arr_);
        bitField0_ |= 0x00010000;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        Response.Arr, Response.Arr.Builder, Response.ArrOrBuilder> arrBuilder_;

    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public java.util.List<Response.Arr> getArrList() {
      if (arrBuilder_ == null) {
        return java.util.Collections.unmodifiableList(arr_);
      } else {
        return arrBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public int getArrCount() {
      if (arrBuilder_ == null) {
        return arr_.size();
      } else {
        return arrBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Response.Arr getArr(int index) {
      if (arrBuilder_ == null) {
        return arr_.get(index);
      } else {
        return arrBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder setArr(
        int index, Response.Arr value) {
      if (arrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrIsMutable();
        arr_.set(index, value);
        onChanged();
      } else {
        arrBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder setArr(
        int index, Response.Arr.Builder builderForValue) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        arr_.set(index, builderForValue.build());
        onChanged();
      } else {
        arrBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder addArr(Response.Arr value) {
      if (arrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrIsMutable();
        arr_.add(value);
        onChanged();
      } else {
        arrBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder addArr(
        int index, Response.Arr value) {
      if (arrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArrIsMutable();
        arr_.add(index, value);
        onChanged();
      } else {
        arrBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder addArr(
        Response.Arr.Builder builderForValue) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        arr_.add(builderForValue.build());
        onChanged();
      } else {
        arrBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder addArr(
        int index, Response.Arr.Builder builderForValue) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        arr_.add(index, builderForValue.build());
        onChanged();
      } else {
        arrBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder addAllArr(
        java.lang.Iterable<? extends Response.Arr> values) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, arr_);
        onChanged();
      } else {
        arrBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder clearArr() {
      if (arrBuilder_ == null) {
        arr_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00010000);
        onChanged();
      } else {
        arrBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Builder removeArr(int index) {
      if (arrBuilder_ == null) {
        ensureArrIsMutable();
        arr_.remove(index);
        onChanged();
      } else {
        arrBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Response.Arr.Builder getArrBuilder(
        int index) {
      return getArrFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Response.ArrOrBuilder getArrOrBuilder(
        int index) {
      if (arrBuilder_ == null) {
        return arr_.get(index);  } else {
        return arrBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public java.util.List<? extends Response.ArrOrBuilder>
         getArrOrBuilderList() {
      if (arrBuilder_ != null) {
        return arrBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(arr_);
      }
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Response.Arr.Builder addArrBuilder() {
      return getArrFieldBuilder().addBuilder(
          Response.Arr.getDefaultInstance());
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public Response.Arr.Builder addArrBuilder(
        int index) {
      return getArrFieldBuilder().addBuilder(
          index, Response.Arr.getDefaultInstance());
    }
    /**
     * <code>repeated .example.Response.Arr arr = 18;</code>
     */
    public java.util.List<Response.Arr.Builder>
         getArrBuilderList() {
      return getArrFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        Response.Arr, Response.Arr.Builder, Response.ArrOrBuilder>
        getArrFieldBuilder() {
      if (arrBuilder_ == null) {
        arrBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            Response.Arr, Response.Arr.Builder, Response.ArrOrBuilder>(
                arr_,
                ((bitField0_ & 0x00010000) == 0x00010000),
                getParentForChildren(),
                isClean());
        arr_ = null;
      }
      return arrBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:example.Response)
  }

  // @@protoc_insertion_point(class_scope:example.Response)
  private static final Response DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Response();
  }

  public static Response getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Response>
      PARSER = new com.google.protobuf.AbstractParser<Response>() {
    public Response parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Response(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Response> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Response> getParserForType() {
    return PARSER;
  }

  public Response getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

