spring:
  application:
    name: federal_client1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/federal_learn?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    timeout: 6000ms
  servlet:
    multipart:
      max-file-size: 200MB # 最大文件上传为200MB
      max-request-size: 500MB
server:
  port: 9000

tencent:
  cos:
    file:
      region: ap-nanjing
      secretId: AKIDiW6XwHl5C8wa1RtBOWWJsGgx761BC9vf
      secretkey: kGXabWDqOl1DQep7HMMF3jS6d2MZovp7
      bucketname: federal-learn-1316343005

#okhttp的信息
ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    max-idle-connections: 200
    keep-alive-duration: 300
