// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.federal_c1.federal_client1.oldgrpc;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * 地址
   * </pre>
   *
   * <code>string url = 2;</code>
   */
  java.lang.String getUrl();
  /**
   * <pre>
   * 地址
   * </pre>
   *
   * <code>string url = 2;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <pre>
   * 哪种方式
   * </pre>
   *
   * <code>string type = 3;</code>
   */
  java.lang.String getType();
  /**
   * <pre>
   * 哪种方式
   * </pre>
   *
   * <code>string type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * 数据
   * </pre>
   *
   * <code>string datainfoReq = 4;</code>
   */
  java.lang.String getDatainfoReq();
  /**
   * <pre>
   * 数据
   * </pre>
   *
   * <code>string datainfoReq = 4;</code>
   */
  com.google.protobuf.ByteString
      getDatainfoReqBytes();
}
