// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: federal.proto

package com.federal_c1.federal_client1.oldgrpc;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <pre>
   * 数据传输的变量
   * </pre>
   *
   * <code>string datainfoRet = 2;</code>
   */
  java.lang.String getDatainfoRet();
  /**
   * <pre>
   * 数据传输的变量
   * </pre>
   *
   * <code>string datainfoRet = 2;</code>
   */
  com.google.protobuf.ByteString
      getDatainfoRetBytes();

  /**
   * <pre>
   * 模型运行的时间
   * </pre>
   *
   * <code>string time = 3;</code>
   */
  java.lang.String getTime();
  /**
   * <pre>
   * 模型运行的时间
   * </pre>
   *
   * <code>string time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();
}
